name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && !contains( github.event.head_commit.message, 'Merge pull request')) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
      - run: npm run report-coverage
      - name: Upload dilithium5 coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/dilithium5/coverage.lcov
          flags: dilithium5
          fail_ci_if_error: true
      - name: Upload mldsa87 coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/mldsa87/coverage.lcov
          flags: mldsa87
          fail_ci_if_error: true
